# Site settings
title: Saul's Blog
email: sdolgin@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal blog where I share thoughts, experiences, and insights
  on various topics including technology, life, and everything in between.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sdolgin.github.io" # the base hostname & protocol for your site
github_username: sdolgin

# Build settings
markdown: kramdown
theme: minima

# Application Insights Configuration
# These values are loaded from environment variables via _plugins/environment.rb
# The plugin will populate this section automatically

# Giscus Comments Configuration
# To enable comments, set enabled: true and configure the repository settings
giscus:
  enabled: false  # Set to true to enable comments
  repository: ""  # GitHub repository in format "owner/repo"
  repository_id: ""  # Optional: Repository ID (can be found in Giscus setup)
  category: "General"  # Discussion category name
  category_id: ""  # Optional: Category ID (can be found in Giscus setup)
  mapping: "pathname"  # How to map pages to discussions (pathname, url, title, og:title)
  strict: "0"  # Use strict title matching (0 or 1)
  reactions_enabled: "1"  # Enable reactions (0 or 1)
  emit_metadata: "0"  # Emit discussion metadata (0 or 1)
  input_position: "bottom"  # Comment input position (top or bottom)
  theme: "preferred_color_scheme"  # Theme (light, dark, preferred_color_scheme, etc.)
  lang: "en"  # Language
  loading: "lazy"  # Loading mode (lazy or eager)

# Only supported plugins for GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Remove unsupported pagination and collections settings for GitHub Pages

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Saul Dolgin"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
